### PR TITLE
link to elm-explorations/test in readme

### PR DESCRIPTION
**Pull request by hrldcpr**
It took me a while to notice the note at the top of the repo; I think the readme is a better place for it.

### CODE REVIEW

**Comment by ondrejsevcik** [comment]
Agree, same issue here.

**Comment by mgold** [comment]
Can you make it a markdown link?

**Comment by hrldcpr** [comment]
@mgold Sure! (Though fyi github turns it into a clickable link anyway)

**Comment by hrldcpr** [comment]
Done ✅

**Comment by drathier** [comment]
Thanks :)

**Pull request merged**
