### PR TITLE
Add new Html runner. Entry point is ElmTest.Runner.Html.runSuite

### PR DESCRIPTION
**Pull request by fredcy**
This is a simple clone/mod of the Console runner. Instead of writing the test output to the Javascript console it outputs Html like a regular Html.App.Program.

### CODE REVIEW

**Comment by eeue56** [comment]
Seems reasonable 👍 do you want a release too?

**Comment by fredcy** [comment]
Sure, I'll publish that change.

**Comment by fredcy** [comment]
I tried, but I don't have permission to push to this repo.

**Comment by eeue56** [comment]
I'll do it in a bit

On Thu, May 12, 2016 at 8:04 PM, Fred Yankowski <notifications@github.com>
wrote:

> I tried, but I don't have permission to push to this repo.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/elm-community/elm-test/pull/2#issuecomment-218837807>
>



-- 
Cheers,
Noah

noah@astraldynamics.co.uk
Astral Dynamics Cyf
Festri Cefn Y Waen, Deiniolen, Caernarfon, Gwynedd LL55 3NB
Company number 07726862
Registered in England and Wales

**Comment by fredcy** [comment]
Please?

**Comment by eeue56** [comment]
@fredcy done as 1.0.1

**Comment by fredcy** [comment]
Thanks.

**Comment by vito** [comment]
Doesn't look like this is actually usable since the package only exports the `ElmTest` module, and nothing in there exports this runner.

**Comment by eeue56** [comment]
That's a good point. @fredcy can you make another PR?

**Comment by eeue56** [comment]
Also weird that this bumped elm-package version. Huh.

**Comment by fredcy** [comment]
Yes, I'll fix it. I had tested it against a local copy of elm-test (listed in 'source-directories') and was importing `ElmTest.Runner.Html` there. I guess I need to test by putting the under-test elm-test in elm-stuff.

**Comment by fredcy** [comment]
See https://github.com/elm-community/elm-test/pull/3

**Pull request merged**
