### PR TITLE
Update README for 4.0.0

### PR DESCRIPTION
**Pull request by mgold**
As per #145, we need an updated README.

I'm cool if this sits until the other work is done.

### CODE REVIEW

**Comment by rtfeldman** [comment]
Unless there are objections, I'm gonna temporarily remove `within` and publish 4.0.0 tonight! Node CLI seems ready and i don't want to block 99% of users on the Html runner. (I'll update it afterwards​.)

**Comment by drathier** [comment]
Sure, go ahead :)

**Comment by mgold** [comment]
Sound good to me - just resolved conflicts so be sure to merge this first!

**Comment by rtfeldman** [comment]
(Update: one last eleventh-hour bug to squash - https://github.com/rtfeldman/node-test-runner/issues/122 - I won't have time to fix it tonight; will try tomorrow night!)

**Pull request merged**
