### PR TITLE
Add a benchmarks directory

### PR DESCRIPTION
**Pull request by jwoudenberg**
This adds some basic benchmarks for the basic Fuzzer-combinators as preparation for the experiment described in #162. I imagine they might be useful for others too.

### CODE REVIEW

**Comment by rtfeldman** [comment]
cc @brianhicks 😄

**Comment by BrianHicks** [comment]
So you're off to a good start but the benchmarks are really artificial. The best thing you could do right now is find some code that actually uses the functions under test and benchmark those snippets instead. And don't repeat calls more than once; the runner will size it properly.

If you see the first benchmark taking a much shorter time than the rest of them, please let me know as I have a workaround. I don't think you'll run into that with this code, though.

**Comment by jwoudenberg** [comment]
I paired a bit on this with Brian last Friday and am pretty happy with these now. This is no longer a WIP as far as I'm concerned, but of course I'm happy to address extra feedback!

**Comment by zwilias** [comment]
This looks really good! ❤️

**Pull request merged**
