### PR TITLE
Add Expect.err

### PR DESCRIPTION
**Pull request by mgold**
A fairly straightforward implementation of #67.

### CODE REVIEW

**Comment by FRosner** [comment]
I think two simple test cases would be sufficient. One where we pass `Ok` and expect a failure and one where we pass `Err` and expect the test to pass.

What do you guys think?

**Comment by mgold** [comment]
I mean, the implementation is pretty obviously correct... but I've added two tests, exactly as you describe, after pushing some refactoring of helpers to master.

@rtfeldman?

**Comment by rtfeldman** [comment]
LGTM! Thanks @mgold! 😍

**Comment by FRosner** [comment]
Thanks a lot @mgold! I love Elm and I believe that this library makes it even greater!

PS: I was not trying to say that your implementation is faulty 😄

**Pull request merged**
