### PR TITLE
Fix list shrinker

### LINKED ISSUE #112: Either Fuzz.list or Fuzz.frequencyOrCrash doesn't shrink properly
**EDIT: after some more analysis, the problem is with lists not shrinking properly and I have a fix.**

I'm getting weird behaviour for [shrinking of `Fuzz.frequencyOrCrash`](https://github.com/elm-community/elm-test/blob/3.1.0/src/Fuzz.elm#L777-L781).

I'm using it to test TEA `update` function with fuzzed list of `Msg` and it doesn't seem to shrink properly - more specifically, **it shows redundant failures instead of just the minimal one.**

When I used an `Fuzz.intRange` ("enum") implementation instead of `Fuzz.frequencyOrCrash`, the issue disappeared, so I have a reason for believing there is a bug in `Fuzz.frequencyOrCrash`.

## Expected output:
```
✗ After taking product, it shouldn't be vended

Given ([AddMoney,Buy],TakeProduct)

    Vended
    ╷
    │ Expect.notEqual
    ╵
    Vended
```

## Actual output:
```
✗ After taking product, it shouldn't be vended

Given ([AddMoney,Buy],TakeProduct)

    Vended
    ╷
    │ Expect.notEqual
    ╵
    Vended


Given ([AddMoney,TakeProduct,Buy],TakeProduct)

    Vended
    ╷
    │ Expect.notEqual
    ╵
    Vended


Given ([AddMoney,TakeProduct,TakeProduct,Buy],TakeProduct)

    Vended
    ╷
    │ Expect.notEqual
    ╵
    Vended


Given ([Buy,AddMoney,TakeProduct,TakeProduct,TakeProduct,Buy,Buy],TakeProduct)

    Vended
    ╷
    │ Expect.notEqual
    ╵
    Vended
```

## [SSCCE >>here<<](https://gist.github.com/Janiczek/04d994667057ff7bd194387db3f36d78)

### PR DESCRIPTION
**Pull request by Janiczek**
Fixes #112.

Previous list shrinker:
  a) shrinked individual values, and
  b) shortened the list by sliding windows of varying lengths over it
     (chose only consecutive values).

That makes eg. [1,2,3] never shrink to [1,3].

This commit fixes this behaviour. The shrinker:
  a) shrinks individual values, as before, and
  b) shortens the list by removing elements at varying positions.

Pro: it generates all possible sublists of the list.
Con: that's substantially more work:

- all possible shortening paths for list of length n:
  `f(n) = n * (f(n-1) + 1); f(1) = 1`

- distinct sublists:
  `f(n) = n^2 - 1`

In a table:
```
length of list: 1  2   3   4    5     6      7       8  ...
possible paths: 1  4  15  64  325  1956  13699  109600  ...
unique paths:   1  3   7  15   31    63    127     255  ...
```

My other pull request (#119 Memoize test results) makes the fuzz test runner
remember and reuse test results, making this pull request more usable :)

### CODE REVIEW

**Comment by Janiczek** [comment]
One question to ask is whether it should try to remove bigger chunks of the list, similar to the removed lines in `shortened` here and to the Shrink.lazyList function in elm-community/shrink. @mgold do you have an opinion or that, or any pointers? Haskell does it IIRC.

**Comment by mgold** [comment]
Honestly I don't have much knowledge or opinion here. If you can show me evidence that it's fast but still shrinks well, it's good.

That said, I implemented the tuple shrinkers by trying to shrink just one of the fuzzers at a time, and then immediately recursing when a successful shrink is made. One downside is that shrinks must be independent. Suppose `A` shrinks to `a` and `B` shrinks to `b`, that `AB` fails the test, and `ab` does too. To find `ab`, either `Ab` or `aB` must fail.

**Comment by Janiczek** [comment]
@mgold Tuple shrinkers are probably independent topic of this, but a quick comment:

I looked at [Haskell's implementation](https://hackage.haskell.org/package/QuickCheck-2.9.2/docs/src/Test-QuickCheck-Arbitrary.html), where it seems the shrinks must be independent too
(find `Arbitrary (a,b)` in the source code)... and I wonder if it couldn't bypass the need for independence with doing
```diff
  shrink (x, y) =
       [ (x', y) | x' <- shrink x ]
    ++ [ (x, y') | y' <- shrink y ]
+   ++ [ (x', y') | x' <- shrink x, y' <- shrink y ]
```
That could possibly propagate automatically into higher n-tuples, seeing as their definitions are (at least in Haskell) using the 2-tuple definition.

Now I don't know **a)** whether that would even work, and **b)** whether that's transferable to Elm version. Is it something you'd like looked at?

**Comment by mgold** [comment]
The problem is that is blows up for higher tuples because you need the cross product of the n fuzzers, shrunk and not.

**Comment by mgold** [comment]
@Janiczek What's the status of this PR?

**Comment by Janiczek** [comment]
This PR is ready, I wanted to wait for the memoizing PR to be merged first so that list fuzzers don't take so much of a performance hit.

**Comment by mgold** [comment]
Well let's make sure #127 doesn't negate those perf gains then.

**Comment by rtfeldman** [comment]
Where did we end up on this one?

**Pull request merged**
