### PR TITLE
Fix Fuzz.string

### PR DESCRIPTION
**Pull request by rtfeldman**
Fixes https://github.com/elm-community/elm-test/issues/50

Also improves docs for `Fuzz.int`, `Fuzz.float`, and `Fuzz.string`

cc @mgold @zkessin

### CODE REVIEW

**Comment by rtfeldman** [comment]
@mgold please merge if this looks good to you! Then we'll have one fewer release blocker. :)

**Comment by mgold** [comment]
I'm not a fan of documenting the exact parameters of `Random.frequency`. That commits them to the interface, when instead the interface should be "our current best guess of what will surface the most bugs".

Code looks good!

**Comment by rtfeldman** [comment]
I think it's appropriate for documentation to cover relevant implementation
details.

It's useful to know whether a given fuzzer can possibly generate a
particular value you know ought to be in the mix. I think "you must read
the source code to answer that question" seems like a worse UX than
answering it in the docs.

Thoughts?

**Comment by mgold** [comment]
Sure, but I think it's possible to do that without putting the exact percentages in docs, which makes  both duplicates logic and implies that they won't change with a patch or minor release. Perhaps:

> It's possible for this fuzzer to generate any 32-bit integer, but favors numbers between -50 and 50 and especially zero.

> This fuzzer will generate strings of up to 1000 printable ASCII characters, but shorter strings are more common, especially the empty string.

**Comment by rtfeldman** [comment]
I can get behind that. 👍

**Comment by rtfeldman** [comment]
Changed in 80db67a5aaeee1431fc3b3aa98da471867e52351

**Comment by mgold** [comment]
Looks good, merging.

**Comment by roine** [comment]
Why do we want to generate empty string?

**Comment by mgold** [comment]
@roine The empty string is considered an edge case, one likely to surface bugs.

**Pull request merged**
