### PR TITLE
Some new functions for lists

### PR DESCRIPTION
**Pull request by zkessin**
create a nonEmptyList, as well as lists of fixed length

### CODE REVIEW

**Comment by zkessin** [comment]
Generate lists of fixed length or non empty lists

**Comment by rtfeldman** [comment]
@zkessin Interesting...have you run into a need for these on personal projects?

**Comment by zkessin** [comment]
In Elm not yet, but in erlang I have used them all the time.

**Comment by zkessin** [comment]
the reason for the non empty list function is for creating a stream of events. Well not the only one

**Comment by rtfeldman** [comment]
> the reason for the non empty list function is for creating a stream of events

What would a stream of events refer to in Elm? I'm not seeing it...

It would help to see the Elm code that would put these to good effect in a current project. 😄

**Comment by zkessin** [comment]
What I was thinking of was building a list of Msg types and then applying them repeatedly to my model to ensure that for any valid sequence of events that it ended in a valid state.

**Comment by rtfeldman** [comment]
Got it. So in that case it a nonempty list fuzzer would be a performance optimization, yeah? (In that it'd avoid test cases where the list was empty and the test didn't do anything.)

**Comment by mgold** [comment]
I don't see a clear use case, the best ideas are in #69, and it's targeting the wrong branch. We'll keep thinking about these ideas though!

**Pull request closed without merging**
