### PR TITLE
number tips

### PR DESCRIPTION
**Pull request by alanhogan**
so people can refer to point number 6 without counting twice ;)

### CODE REVIEW

**Comment by mgold** [comment]
I hear the "being able to refer to tips" benefit, but will  that be obvious to people reading the guide?

At the very least, I'd like these numbered correctly in markdown.

**Comment by rtfeldman** [comment]
I'm 👍 on this as-is.

I think it's more confusing when Markdown lists attempt to number and then get out of sync (e.g. because someone adds something between `#4` and `#5`, forgets to change `#6` and higher, but the diff on the PR doesn't show that we now have a duplicate `#5` and now the Markdown file is confusingly mis-numbered), and this seems like it'd have the potential for minor additions over time that would be prone to that sort of mistake.

**Comment by alanhogan** [comment]
I made the PR because exactly the described hypothetical scenario had played out — we counted differently — and we agreed it’d be useful if we numbered it here.

Do please merge if the community is okay with it!

**Comment by rtfeldman** [comment]
@mgold cool with you to merge this?

**Comment by mgold** [comment]
...sure.

**Comment by rtfeldman** [comment]
Cool, thanks @alanhogan!

**Pull request merged**
